[package]
name = "test-nft"
version = "0.1.0"
authors = ["Illia Polosukhin <illia.polosukhin@gmail.com>", "Rashi Abramson <roshkins@gmail.com>"]
edition = "2018"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]


[dependencies]
near-sdk = "3.1.0"
near-contract-standards = "3.1.0"
