[package]
name = "sputnikdao2"
version = "2.0.0"
authors = ["Sputnik Devs <near-daos@protonmail.com>"]
edition = "2018"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = {version = "4.0.0-pre.2", features = ["unstable"]}
near-contract-standards = "4.0.0-pre.2"
hex = "0.4.2"

[dev-dependencies]
near-sdk-sim = "4.0.0-pre.2"
test-token = { path = "../test-token" }
test-nft = { path = "../test-nft" }
sputnik-staking = { path = "../sputnik-staking" }